[[_community_dsls]]
== 社区 DSLs

=== ElasticsearchDSL

https://github.com/ongr-io/ElasticsearchDSL[Link: ElasticsearchDSL]

[quote, ElasticsearchDSL]
__________________________
引入 Elasticsearch DSL 类库，目的是为 Elasticsearch bundle 和 Elasticsearch PHP 客户端提供对象查询语句构造器。你可以轻松地构造任何 Elasticsearch 查询语句且转变语句为数组。
__________________________

=== elasticsearcher

https://github.com/madewithlove/elasticsearcher[Link: elasticsearcher]

[quote, elasticsearcher]
__________________________
这个独立的包是位于 Elasticsearch PHP 客户端之上的一个轻量级的封装。它主要的目的是让应用中的查询语句和索引的构造更为简易。它并非要隐藏或替代 Elasticsearch PHP 客户端的功能。
__________________________

== Community Integrations

=== Symfony

==== ONGR Elasticsearch Bundle

https://github.com/ongr-io/ElasticsearchBundle[Link: ONGR Elasticsearch Bundle]

[quote, ONGR Elasticsearch Bundle]
__________________________
Elasticsearch Bundle was created in order to serve the need for professional elasticsearch
integration with enterprise level Symfony 2 systems. This bundle is:

- Supported by ONGR.io development team.
- Uses the official elasticsearch-php client.
- Ensures full integration with Symfony 2 framework.

Technical goodies:

- Provides nestable and DSL query builder to be executed by type repository services.
- Uses Doctrine-like document / entities document-object mapping using annotations.
- Query results iterators are provided for your convenience.
- Registers console commands for index and types management and data import / export.
- Designed in an extensible way for all your custom needs.
__________________________


==== FOS Elastica Bundle

https://github.com/FriendsOfSymfony/FOSElasticaBundle[Link: FOS Elastica Bundle]

[quote, FOS Elastica Bundle]
__________________________
This bundle provides integration with https://github.com/ruflin/Elastica[Link: Elastica] for Symfony. Features include:

- Integrates the Elastica library into a Symfony environment
- Automatically generate mappings using a serializer
- Listeners for Doctrine events for automatic indexing
__________________________


=== Drupal

==== Elasticsearch Connector

https://www.drupal.org/project/elasticsearch_connector[Link: Elasticsearch Connector]

[quote, Elasticsearch Connector]
__________________________
Elasticsearch Connector is a set of modules designed to build a full Elasticsearch eco system in Drupal.
__________________________

=== Laravel

==== shift31/Laravel-Elasticsearch

https://github.com/shift31/laravel-elasticsearch[Link: shift31/Laravel-Elasticsearch]

[quote, Laravel-Elasticsearch]
__________________________
This is a Laravel (4+) Service Provider for the official Elasticsearch low-level client.
__________________________


==== cviebrock/Laravel-Elasticsearch

https://github.com/cviebrock/laravel-elasticsearch[Link: cviebrock/Laravel-Elasticsearch]

[quote, Laravel-Elasticsearch]
__________________________
An easy way to use the official Elastic Search client in your Laravel applications.
__________________________


==== Plastic

https://github.com/sleimanx2/plastic[Link: Plastic]

[quote, Plastic]
__________________________
Plastic is an Elasticsearch ODM and mapper for Laravel. It renders the developer experience more enjoyable while using Elasticsearch, by providing a fluent syntax for mapping, querying, and storing eloquent models.
__________________________

=== Helper

==== Index Helper

https://github.com/Nexucis/es-php-index-helper[Link: nexucis/es-php-index-helper]

[quote, Index Helper]
_____________________
This helper is a light library which wrap the official client elasticsearch-php. It will help you to manage your ES Indices with no downtime.
This helper implements the philosophy described in the https://www.elastic.co/guide/en/elasticsearch/guide/master/index-aliases.html[official documentation]
which can be summarized in a few words : *use alias instead of index directly*
_____________________
